# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Download Latest Snapshot

on:
  push:
    branches: [ major-update ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Deploy with Gradle
      run: ./gradlew deploy
    - name: Tag Repo
      uses: richardsimko/update-tag@master
      with:
        tag_name: major-update-snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: ncipollo/release-action@v1.6.1
      with:
        artifacts: "Luminescent.jar"
        allowUpdates: true
        name: "Major Update Snapshot"
        commit: ${{ steps.extract_branch.outputs.branch }}
        prerelease: true
        replaceArtifacts: true
        tag: "major-update-snapshot"
        token: ${{ secrets.GITHUB_TOKEN }}
